### ISSUE TITLE
Select with ng-model prefilled with null value is not working correctly

### ISSUE THREAD

**Issue by palodelincak** [bvaughn/angular-form-for#129] opened 2015-06-24 14:54 UTC
Hello again! First of all, as I wrote in #125 thanks for you work on this plugin! I tested your newest release  and I found one small bug - which was reported before but you probably forgot on this one.

Take a look at this Plunk:
http://plnkr.co/edit/hEsagnHsQ6OH1ETncUWe?p=preview

When `ng-model` is prefilled with `null` value, which is not present in `options`, the `placeholder` is displayed. This is correct. But if select has `allow-blank`, the blank option is added also. There should be only placeholder or only blank options - not both of these.

Example scenario:
When I select value from options (for example `1`) the placeholder will go away and only blank option is present. After this, when I select blank option, then another blank option is appended to options.

Can you take a look at this case please? All falsy values like `''`, `undefined`, `null` should be treated exactly the same.

PS: Excuse me for being pain in the ass with last few bugs :-)

**Comment by bvaughn** [comment] 2015-06-24 15:09
Ah, okay. Thanks for noticing this and sorry for the regression. Refactorings can be like that.. :)
I'll try to get to this faster this time around. Should be much easier now that the code's  been cleaned up.

**Comment by bvaughn** [comment] 2015-06-25 03:43
Hey @palodelincak. I just took a look at your problem and I'm unable to reproduce it locally or in Plunker using the new 4.0.0 release. For example: http://plnkr.co/edit/6mnzzvzvrfYm2PL5PIVR?p=preview

I believe you're talking about field 5- which is indeed broken in your plunker- but it's working fine in the one I linked to as well as my local copy.

**Edit**: Interestingly enough, I noticed that you were using Angular 1.3.15 while I've been developing and testing with Angular 1.4.1. Sure enough, changing your test Plunker to 1.4.1 resolves the issue. Hm.

**Comment by palodelincak** [comment] 2015-06-25 08:25
Oh, well... so it's related to Angular version and it has nothing to do with your plugin? So the only way to fix this is to upgrade Angular?

**Comment by bvaughn** [comment] 2015-06-25 13:47
No. I wasn't saying that. Just pointing out that it has something to do
with the Angular version. I'll have to do done more digging.

**Comment by bvaughn** [comment] 2015-06-27 01:20
Looking at this again this evening. From what I can tell, formFor is setting the correct `bindableOptions` and `ngModel` values, but Angular 1.2.x-1.3.x is generating an extra option:

```html
<select ng-model="model.bindable"
        ng-options="option[valueAttribute] as option[labelAttribute] for option in bindableOptions">
  <option value="" selected="selected" label=""></option> <!-- Where is this one coming from? -->
  <option value="0" selected="selected" label="Custom placeholder">Custom placeholder</option>
  <option value="1" label="1">1</option>
  <option value="2" label="2">2</option>
  <option value="3" label="3">3</option>
</select>
```

**Comment by bvaughn** [comment] 2015-06-27 01:28
It's also interesting to note that even when I select a non-empty option (with Angular 1.3.x) the markup still has 2 selected options:

```html
<select ng-model="model.bindable"
        ng-options="option[valueAttribute] as option[labelAttribute] for option in bindableOptions">
  <option value="0" selected="selected" label=""></option> <!-- Why is this also selected? -->
  <option value="1" selected="selected" label="1">1</option>
  <option value="2" label="2">2</option>
  <option value="3" label="3">3</option>
</select>
```

**Comment by bvaughn** [comment] 2015-06-27 02:05
Okay, I *think* I have a solution here that doesn't cause a regression and that works with Angular 1.2.x-1.3.x. Essentially it involves converting any incoming model values of `null`, `undefined`, or empty string to `undefined`. This prevents Angular from creating the phantom, selected `<option>`. It's a little bizarre though...

**Comment by bvaughn** [comment] 2015-06-27 02:16
Pushed a fix and I'll make a release this evening. I *hope* this resolves your issue but please let me know if not. :)

**Closed** 2015-06-27 02:15 UTC

**Comment by bvaughn** [comment] 2015-06-27 03:16
Release [4.0.1](https://github.com/bvaughn/angular-form-for/releases/tag/4.0.1) is out with this fix.
